<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="SVG"
    nsURI="SVG&amp;Geometry"
    nsPrefix="svg">
  <eAnnotations
      source="http://www.eclipse.org/OCL/Import">
    <details
        key="ecore"
        value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Group">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="class"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="content"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="movable"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ClipPath"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Rectangle">
    <eOperations
        name="enlarge"
        eType="#//Rectangle">
      <eParameters
          name="size"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations
        name="enlarge"
        eType="#//Rectangle">
      <eParameters
          name="width"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters
          name="height"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations
        name="enlarge"
        eType="#//Rectangle">
      <eParameters
          name="left"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters
          name="top"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters
          name="right"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters
          name="bottom"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations
        name="mustContain"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters
          name="contained"
          eType="#//Rectangle"/>
    </eOperations>
    <eOperations
        name="mustContainX"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters
          name="x"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="width"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="height"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="center"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="top"
        eType="#//Line"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="right"
        eType="#//Line"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="bottom"
        eType="#//Line"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="left"
        eType="#//Line"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="x"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="y"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="bottomLeft"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="bottomRight"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="topLeft"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="topRight"
        eType="#//Point"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Text"
      eSuperTypes="#//Rectangle">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="text"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Line">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="p1"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="p2"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="center"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="x1"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="x2"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="y1"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="y2"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Point">
    <eOperations
        name="dy"
        eType="#//Point">
      <eParameters
          name="value"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations
        name="dx"
        eType="#//Point">
      <eParameters
          name="value"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations
        name="plus"
        eType="#//Point">
      <eParameters
          name="x"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters
          name="y"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations
        name="onSegment"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters
          name="segment"
          eType="#//Line"/>
    </eOperations>
    <eOperations
        name="stay"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters
          name="strength"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="x"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="y"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Circle">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="r"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="center"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="topLeft"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="top"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="topRight"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="right"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="bottomRight"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="bottom"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="bottomLeft"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="left"
        eType="#//Point"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="cx"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="cy"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Polygon">
    <eOperations
        name="pointEq"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters
          name="index"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters
          name="point"
          eType="#//Point"/>
    </eOperations>
    <eOperations
        name="pointEq"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters
          name="index"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters
          name="x"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters
          name="y"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations
        name="constrainTEllipse"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters
          name="x"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters
          name="y"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters
          name="size"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters
          name="interFociX"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters
          name="interFociY"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations
        name="constrainTEllipse"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters
          name="x"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters
          name="y"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters
          name="size"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters
          name="interFociX"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="center"
        eType="#//Point"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Title"/>
</ecore:EPackage>
