<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="xbase" nsURI="http://www.eclipse.org/xtext/xbase/Xbase" nsPrefix="xbase">
    <eClassifiers xsi:type="ecore:EClass" name="XExpression" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="XIfExpression" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="if" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#/0/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSwitchExpression" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="switch" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
          eType="#/0/XCasePart" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaredParam" eType="#/1/JvmFormalParameter"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XCasePart">
      <eStructuralFeatures xsi:type="ecore:EReference" name="case" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeGuard" eType="#/1/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fallThrough" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XBlockExpression" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
          eType="#/0/XExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XVariableDeclaration" eSuperTypes="#/0/XExpression #/1/JvmIdentifiableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/1/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XAbstractFeatureCall" abstract="true"
        eSuperTypes="#/0/XExpression">
      <eOperations name="getConcreteSyntaxFeatureName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getExplicitArguments" upperBound="-1" eType="#/0/XExpression"/>
      <eOperations name="isExplicitOperationCallOrBuilderSyntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getActualReceiver" eType="#/0/XExpression"/>
      <eOperations name="getActualArguments" upperBound="-1" eType="#/0/XExpression"/>
      <eOperations name="isStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isPackageFragment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isTypeLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isOperation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="#/1/JvmIdentifiableElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1"
          eType="#/1/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implicitReceiver" eType="#/0/XExpression"
          volatile="true" transient="true" derived="true" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="invalidFeatureIssueCode"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implicitFirstArgument"
          eType="#/0/XExpression" volatile="true" transient="true" derived="true"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XMemberFeatureCall" eSuperTypes="#/0/XAbstractFeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="memberCallTarget" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="memberCallArguments"
          upperBound="-1" eType="#/0/XExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitOperationCall"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullSafe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="staticWithDeclaringType"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageFragment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XFeatureCall" eSuperTypes="#/0/XAbstractFeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="featureCallArguments"
          upperBound="-1" eType="#/0/XExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitOperationCall"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageFragment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XConstructorCall" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constructor" eType="#/1/JvmConstructor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#/0/XExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1"
          eType="#/1/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="invalidFeatureIssueCode"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitConstructorCall"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="anonymousClassConstructorCall"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XBooleanLiteral" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTrue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XNullLiteral" eSuperTypes="#/0/XExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="XNumberLiteral" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XStringLiteral" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XCollectionLiteral" abstract="true"
        eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#/0/XExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XListLiteral" eSuperTypes="#/0/XCollectionLiteral"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSetLiteral" eSuperTypes="#/0/XCollectionLiteral"/>
    <eClassifiers xsi:type="ecore:EClass" name="XClosure" eSuperTypes="#/0/XExpression">
      <eOperations name="getFormalParameters" upperBound="-1" eType="#/1/JvmFormalParameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaredFormalParameters"
          upperBound="-1" eType="#/1/JvmFormalParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitSyntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implicitFormalParameters"
          upperBound="-1" eType="#/1/JvmFormalParameter" volatile="true" transient="true"
          derived="true" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XCastedExpression" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/1/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#/0/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XBinaryOperation" eSuperTypes="#/0/XAbstractFeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="reassignFirstArgument"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XUnaryOperation" eSuperTypes="#/0/XAbstractFeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#/0/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XPostfixOperation" eSuperTypes="#/0/XAbstractFeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#/0/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XForLoopExpression" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="forExpression" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eachExpression" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaredParam" eType="#/1/JvmFormalParameter"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XBasicForLoopExpression" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eachExpression" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initExpressions" upperBound="-1"
          eType="#/0/XExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="updateExpressions" upperBound="-1"
          eType="#/0/XExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XAbstractWhileExpression" abstract="true"
        eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#/0/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XDoWhileExpression" eSuperTypes="#/0/XAbstractWhileExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="XWhileExpression" eSuperTypes="#/0/XAbstractWhileExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="XTypeLiteral" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#/1/JvmType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrayDimensions" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XInstanceOfExpression" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#/1/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#/0/XExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XThrowExpression" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/0/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XTryCatchFinallyExpression" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="finallyExpression" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="catchClauses" upperBound="-1"
          eType="#/0/XCatchClause" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XCatchClause">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaredParam" eType="#/1/JvmFormalParameter"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XAssignment" eSuperTypes="#/0/XAbstractFeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="assignable" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="staticWithDeclaringType"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XReturnExpression" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/0/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSynchronizedExpression" eSuperTypes="#/0/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="#/0/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/0/XExpression"
          containment="true"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="types" nsURI="http://www.eclipse.org/xtext/common/JavaVMTypes"
      nsPrefix="types">
    <eClassifiers xsi:type="ecore:EClass" name="JvmIdentifiableElement" abstract="true">
      <eOperations name="getIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getSimpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="innerClassDelimiter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmType" abstract="true" eSuperTypes="#/1/JvmIdentifiableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmVoid" eSuperTypes="#/1/JvmType"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmComponentType" abstract="true"
        eSuperTypes="#/1/JvmType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arrayType" eType="#/1/JvmArrayType"
          containment="true" eOpposite="#/1/JvmArrayType/componentType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmPrimitiveType" eSuperTypes="#/1/JvmComponentType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="simpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmArrayType" eSuperTypes="#/1/JvmComponentType">
      <eOperations name="getDimensions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentType" eType="#/1/JvmComponentType"
          eOpposite="#/1/JvmComponentType/arrayType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmDeclaredType" abstract="true" eSuperTypes="#/1/JvmMember #/1/JvmComponentType">
      <eOperations name="getDeclaredOperations" lowerBound="1">
        <eGenericType eClassifier="#/1/Iterable">
          <eTypeArguments eClassifier="#/1/JvmOperation"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getDeclaredFields" lowerBound="1">
        <eGenericType eClassifier="#/1/Iterable">
          <eTypeArguments eClassifier="#/1/JvmField"/>
        </eGenericType>
      </eOperations>
      <eOperations name="findAllFeaturesByName" lowerBound="1">
        <eGenericType eClassifier="#/1/Iterable">
          <eTypeArguments eClassifier="#/1/JvmFeature"/>
        </eGenericType>
        <eParameters name="simpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getAllFeatures" lowerBound="1">
        <eGenericType eClassifier="#/1/Iterable">
          <eTypeArguments eClassifier="#/1/JvmFeature"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getExtendedInterfaces">
        <eGenericType eClassifier="#/1/Iterable">
          <eTypeArguments eClassifier="#/1/JvmTypeReference"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getExtendedClass" eType="#/1/JvmTypeReference"/>
      <eOperations name="isInstantiateable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="findAllNestedTypesByName">
        <eGenericType eClassifier="#/1/Iterable">
          <eTypeArguments eClassifier="#/1/JvmDeclaredType"/>
        </eGenericType>
        <eParameters name="simpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="isLocal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getDeclaredConstructors" lowerBound="1">
        <eGenericType eClassifier="#/1/Iterable">
          <eTypeArguments eClassifier="#/1/JvmConstructor"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getAllNestedTypes" lowerBound="1">
        <eGenericType eClassifier="#/1/Iterable">
          <eTypeArguments eClassifier="#/1/JvmDeclaredType"/>
        </eGenericType>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="superTypes" upperBound="-1"
          eType="#/1/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
          eType="#/1/JvmMember" containment="true" eOpposite="#/1/JvmMember/declaringType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmTypeParameter" eSuperTypes="#/1/JvmComponentType #/1/JvmConstraintOwner">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declarator" eType="#/1/JvmTypeParameterDeclarator"
          eOpposite="#/1/JvmTypeParameterDeclarator/typeParameters"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmTypeParameterDeclarator" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1"
          eType="#/1/JvmTypeParameter" containment="true" eOpposite="#/1/JvmTypeParameter/declarator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmConstraintOwner" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#/1/JvmTypeConstraint" containment="true" eOpposite="#/1/JvmTypeConstraint/owner"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmTypeConstraint" abstract="true">
      <eOperations name="getIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getSimpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="innerClassDelimiter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeReference" eType="#/1/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#/1/JvmConstraintOwner"
          eOpposite="#/1/JvmConstraintOwner/constraints"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmUpperBound" eSuperTypes="#/1/JvmTypeConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmLowerBound" eSuperTypes="#/1/JvmTypeConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmAnnotationType" eSuperTypes="#/1/JvmDeclaredType"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmEnumerationType" eSuperTypes="#/1/JvmDeclaredType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
          eType="#/1/JvmEnumerationLiteral" changeable="false" volatile="true" transient="true"
          derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmEnumerationLiteral" eSuperTypes="#/1/JvmField">
      <eOperations name="getEnumType" eType="#/1/JvmEnumerationType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmGenericType" eSuperTypes="#/1/JvmDeclaredType #/1/JvmTypeParameterDeclarator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interface" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strictFloatingPoint"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="anonymous" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmTypeReference" abstract="true">
      <eOperations name="getType" eType="#/1/JvmType"/>
      <eOperations name="getIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getSimpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="innerClassDelimiter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
      </eOperations>
      <eOperations name="accept">
        <eGenericType eTypeParameter="#/1/JvmTypeReference/accept/Result"/>
        <eTypeParameters name="Result"/>
        <eParameters name="visitor">
          <eGenericType eClassifier="#/1/ITypeReferenceVisitor">
            <eTypeArguments eTypeParameter="#/1/JvmTypeReference/accept/Result"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eOperations name="accept">
        <eGenericType eTypeParameter="#/1/JvmTypeReference/accept.1/Result"/>
        <eTypeParameters name="Parameter"/>
        <eTypeParameters name="Result"/>
        <eParameters name="visitor">
          <eGenericType eClassifier="#/1/ITypeReferenceVisitorWithParameter">
            <eTypeArguments eTypeParameter="#/1/JvmTypeReference/accept.1/Parameter"/>
            <eTypeArguments eTypeParameter="#/1/JvmTypeReference/accept.1/Result"/>
          </eGenericType>
        </eParameters>
        <eParameters name="parameter">
          <eGenericType eTypeParameter="#/1/JvmTypeReference/accept.1/Parameter"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmParameterizedTypeReference" eSuperTypes="#/1/JvmTypeReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#/1/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/1/JvmType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmGenericArrayTypeReference" eSuperTypes="#/1/JvmTypeReference">
      <eOperations name="getDimensions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getType" eType="#/1/JvmArrayType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentType" eType="#/1/JvmTypeReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmWildcardTypeReference" eSuperTypes="#/1/JvmTypeReference #/1/JvmConstraintOwner"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmAnyTypeReference" eSuperTypes="#/1/JvmTypeReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/1/JvmType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmMultiTypeReference" eSuperTypes="#/1/JvmCompoundTypeReference"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmMember" abstract="true" eSuperTypes="#/1/JvmAnnotationTarget">
      <eOperations name="internalSetIdentifier" ordered="false" lowerBound="1">
        <eParameters name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaringType" eType="#/1/JvmDeclaredType"
          eOpposite="#/1/JvmDeclaredType/members"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#/1/JvmVisibility"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="simpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="deprecated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmFeature" abstract="true" eSuperTypes="#/1/JvmMember">
      <eOperations name="isStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="localClasses" upperBound="-1"
          eType="#/1/JvmGenericType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmField" eSuperTypes="#/1/JvmFeature">
      <eOperations name="getConstantValueAsLong" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eOperations name="getConstantValueAsInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getConstantValueAsShort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
      <eOperations name="getConstantValueAsByte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
      <eOperations name="getConstantValueAsDouble" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eOperations name="getConstantValueAsFloat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eOperations name="getConstantValueAsChar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
      <eOperations name="getConstantValueAsBoolean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getConstantValueAsString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/1/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="volatile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constantValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmExecutable" abstract="true" eSuperTypes="#/1/JvmFeature #/1/JvmTypeParameterDeclarator">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#/1/JvmFormalParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exceptions" upperBound="-1"
          eType="#/1/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="varArgs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmConstructor" eSuperTypes="#/1/JvmExecutable"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmOperation" eSuperTypes="#/1/JvmExecutable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#/1/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#/1/JvmAnnotationValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="synchronized" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="native" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strictFloatingPoint"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmFormalParameter" eSuperTypes="#/1/JvmAnnotationTarget">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterType" eType="#/1/JvmTypeReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmAnnotationTarget" abstract="true"
        eSuperTypes="#/1/JvmIdentifiableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
          eType="#/1/JvmAnnotationReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmAnnotationReference">
      <eOperations name="getValues" upperBound="-1" eType="#/1/JvmAnnotationValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" eType="#/1/JvmAnnotationType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="explicitValues" upperBound="-1"
          eType="#/1/JvmAnnotationValue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmAnnotationValue" abstract="true">
      <eOperations name="getValueName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#/1/JvmOperation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmIntAnnotationValue" eSuperTypes="#/1/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmBooleanAnnotationValue" eSuperTypes="#/1/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmByteAnnotationValue" eSuperTypes="#/1/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmShortAnnotationValue" eSuperTypes="#/1/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmLongAnnotationValue" eSuperTypes="#/1/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmDoubleAnnotationValue" eSuperTypes="#/1/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmFloatAnnotationValue" eSuperTypes="#/1/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmCharAnnotationValue" eSuperTypes="#/1/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmStringAnnotationValue" eSuperTypes="#/1/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmTypeAnnotationValue" eSuperTypes="#/1/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
          eType="#/1/JvmTypeReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmAnnotationAnnotationValue" eSuperTypes="#/1/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
          eType="#/1/JvmAnnotationReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmEnumAnnotationValue" eSuperTypes="#/1/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" unique="false"
          upperBound="-1" eType="#/1/JvmEnumerationLiteral"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmDelegateTypeReference" eSuperTypes="#/1/JvmTypeReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" eType="#/1/JvmTypeReference"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmSpecializedTypeReference" abstract="true"
        eSuperTypes="#/1/JvmTypeReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="equivalent" eType="#/1/JvmTypeReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmSynonymTypeReference" eSuperTypes="#/1/JvmCompoundTypeReference"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmUnknownTypeReference" eSuperTypes="#/1/JvmTypeReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmCompoundTypeReference" abstract="true"
        eSuperTypes="#/1/JvmTypeReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/1/JvmType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
          eType="#/1/JvmTypeReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmCustomAnnotationValue" eSuperTypes="#/1/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmInnerTypeReference" eSuperTypes="#/1/JvmParameterizedTypeReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="outer" eType="#/1/JvmParameterizedTypeReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="JvmVisibility">
      <eLiterals name="DEFAULT"/>
      <eLiterals name="PRIVATE" value="1"/>
      <eLiterals name="PROTECTED" value="2"/>
      <eLiterals name="PUBLIC" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Iterable">
      <eTypeParameters name="E"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ITypeReferenceVisitor">
      <eTypeParameters name="Result"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ITypeReferenceVisitorWithParameter">
      <eTypeParameters name="Parameter"/>
      <eTypeParameters name="Result"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
