<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="xtend" nsURI="http://www.eclipse.org/xtend" nsPrefix="xtend">
    <eClassifiers xsi:type="ecore:EClass" name="XtendFile">
      <eStructuralFeatures xsi:type="ecore:EReference" name="importSection" eType="#/1/XImportSection"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="xtendTypes" upperBound="-1"
          eType="#/0/XtendTypeDeclaration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XtendClass" eSuperTypes="#/0/XtendTypeDeclaration">
      <eOperations name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isStrictFloatingPoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extends" eType="#/4/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implements" upperBound="-1"
          eType="#/4/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1"
          eType="#/4/JvmTypeParameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XtendAnnotationTarget" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
          eType="#/2/XAnnotation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XtendMember" eSuperTypes="#/0/XtendAnnotationTarget">
      <eOperations name="getVisibility" eType="#/4/JvmVisibility"/>
      <eOperations name="getDeclaredVisibility" eType="#/4/JvmVisibility"/>
      <eOperations name="isStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isFinal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotationInfo" eType="#/0/XtendAnnotationTarget"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifiers" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaringType" eType="#/0/XtendTypeDeclaration"
          eOpposite="#/0/XtendTypeDeclaration/members"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XtendFunction" eSuperTypes="#/0/XtendExecutable">
      <eOperations name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isOverride" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isDispatch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isStrictFloatingPoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isNative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isSynchonized" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#/4/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="createExtensionInfo"
          eType="#/0/CreateExtensionInfo" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XtendField" eSuperTypes="#/0/XtendMember">
      <eOperations name="isExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isVolatile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isTransient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/4/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialValue" eType="#/3/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XtendParameter" eSuperTypes="#/0/XtendAnnotationTarget">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterType" eType="#/4/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="varArg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RichString" eSuperTypes="#/3/XBlockExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="RichStringLiteral" eSuperTypes="#/3/XStringLiteral"/>
    <eClassifiers xsi:type="ecore:EClass" name="RichStringForLoop" eSuperTypes="#/3/XForLoopExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="separator" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="before" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="after" eType="#/3/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RichStringIf" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="if" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseIfs" upperBound="-1"
          eType="#/0/RichStringElseIf" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#/3/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RichStringElseIf">
      <eStructuralFeatures xsi:type="ecore:EReference" name="if" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#/3/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateExtensionInfo">
      <eStructuralFeatures xsi:type="ecore:EReference" name="createExpression" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="it"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XtendConstructor" eSuperTypes="#/0/XtendExecutable"/>
    <eClassifiers xsi:type="ecore:EClass" name="XtendTypeDeclaration" eSuperTypes="#/0/XtendMember">
      <eOperations name="isAnonymous" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isLocal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
          eType="#/0/XtendMember" containment="true" eOpposite="#/0/XtendMember/declaringType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XtendAnnotationType" eSuperTypes="#/0/XtendTypeDeclaration"/>
    <eClassifiers xsi:type="ecore:EClass" name="XtendInterface" eSuperTypes="#/0/XtendTypeDeclaration">
      <eOperations name="isStrictFloatingPoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
          eType="#/4/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1"
          eType="#/4/JvmTypeParameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XtendEnum" eSuperTypes="#/0/XtendTypeDeclaration"/>
    <eClassifiers xsi:type="ecore:EClass" name="XtendEnumLiteral" eSuperTypes="#/0/XtendMember">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XtendVariableDeclaration" eSuperTypes="#/3/XVariableDeclaration">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XtendFormalParameter" eSuperTypes="#/4/JvmFormalParameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XtendExecutable" abstract="true" eSuperTypes="#/0/XtendMember">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exceptions" upperBound="-1"
          eType="#/4/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1"
          eType="#/4/JvmTypeParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#/0/XtendParameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnonymousClass" eSuperTypes="#/3/XExpression #/0/XtendTypeDeclaration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constructorCall" eType="#/3/XConstructorCall"
          containment="true"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="xtype" nsURI="http://www.eclipse.org/xtext/xbase/Xtype" nsPrefix="xtype">
    <eClassifiers xsi:type="ecore:EClass" name="XFunctionTypeRef" eSuperTypes="#/4/JvmSpecializedTypeReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="paramTypes" upperBound="-1"
          eType="#/4/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#/4/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/4/JvmType"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceContext" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XComputedTypeReference" eSuperTypes="#/4/JvmSpecializedTypeReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeProvider" eType="#/1/IJvmTypeReferenceProvider"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XImportSection">
      <eStructuralFeatures xsi:type="ecore:EReference" name="importDeclarations" upperBound="-1"
          eType="#/1/XImportDeclaration" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XImportDeclaration">
      <eOperations name="getImportedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getImportedTypeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="wildcard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="importedType" eType="#/4/JvmDeclaredType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="memberName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="IJvmTypeReferenceProvider"/>
  </ecore:EPackage>
  <ecore:EPackage name="xAnnotations" nsURI="http://www.eclipse.org/Xtext/Xbase/XAnnotations"
      nsPrefix="xAnnotations">
    <eClassifiers xsi:type="ecore:EClass" name="XAnnotation" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementValuePairs" upperBound="-1"
          eType="#/2/XAnnotationElementValuePair" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotationType" eType="#/4/JvmType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#/3/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XAnnotationElementValuePair">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#/4/JvmOperation"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="xbase" nsURI="http://www.eclipse.org/xtext/xbase/Xbase" nsPrefix="xbase">
    <eClassifiers xsi:type="ecore:EClass" name="XExpression" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="XIfExpression" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="if" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#/3/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSwitchExpression" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="switch" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
          eType="#/3/XCasePart" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaredParam" eType="#/4/JvmFormalParameter"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XCasePart">
      <eStructuralFeatures xsi:type="ecore:EReference" name="case" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeGuard" eType="#/4/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fallThrough" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XBlockExpression" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
          eType="#/3/XExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XVariableDeclaration" eSuperTypes="#/3/XExpression #/4/JvmIdentifiableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/4/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XAbstractFeatureCall" abstract="true"
        eSuperTypes="#/3/XExpression">
      <eOperations name="getConcreteSyntaxFeatureName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getExplicitArguments" upperBound="-1" eType="#/3/XExpression"/>
      <eOperations name="isExplicitOperationCallOrBuilderSyntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getActualReceiver" eType="#/3/XExpression"/>
      <eOperations name="getActualArguments" upperBound="-1" eType="#/3/XExpression"/>
      <eOperations name="isStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isPackageFragment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isTypeLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isOperation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="#/4/JvmIdentifiableElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1"
          eType="#/4/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implicitReceiver" eType="#/3/XExpression"
          volatile="true" transient="true" derived="true" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="invalidFeatureIssueCode"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implicitFirstArgument"
          eType="#/3/XExpression" volatile="true" transient="true" derived="true"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XMemberFeatureCall" eSuperTypes="#/3/XAbstractFeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="memberCallTarget" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="memberCallArguments"
          upperBound="-1" eType="#/3/XExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitOperationCall"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullSafe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="staticWithDeclaringType"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageFragment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XFeatureCall" eSuperTypes="#/3/XAbstractFeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="featureCallArguments"
          upperBound="-1" eType="#/3/XExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitOperationCall"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageFragment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XConstructorCall" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constructor" eType="#/4/JvmConstructor"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#/3/XExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1"
          eType="#/4/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="invalidFeatureIssueCode"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitConstructorCall"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="anonymousClassConstructorCall"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XBooleanLiteral" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTrue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XNullLiteral" eSuperTypes="#/3/XExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="XNumberLiteral" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XStringLiteral" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XCollectionLiteral" abstract="true"
        eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#/3/XExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XListLiteral" eSuperTypes="#/3/XCollectionLiteral"/>
    <eClassifiers xsi:type="ecore:EClass" name="XSetLiteral" eSuperTypes="#/3/XCollectionLiteral"/>
    <eClassifiers xsi:type="ecore:EClass" name="XClosure" eSuperTypes="#/3/XExpression">
      <eOperations name="getFormalParameters" upperBound="-1" eType="#/4/JvmFormalParameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaredFormalParameters"
          upperBound="-1" eType="#/4/JvmFormalParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitSyntax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implicitFormalParameters"
          upperBound="-1" eType="#/4/JvmFormalParameter" volatile="true" transient="true"
          derived="true" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XCastedExpression" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/4/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#/3/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XBinaryOperation" eSuperTypes="#/3/XAbstractFeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="reassignFirstArgument"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XUnaryOperation" eSuperTypes="#/3/XAbstractFeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#/3/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XPostfixOperation" eSuperTypes="#/3/XAbstractFeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#/3/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XForLoopExpression" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="forExpression" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eachExpression" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaredParam" eType="#/4/JvmFormalParameter"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XBasicForLoopExpression" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eachExpression" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initExpressions" upperBound="-1"
          eType="#/3/XExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="updateExpressions" upperBound="-1"
          eType="#/3/XExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XAbstractWhileExpression" abstract="true"
        eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#/3/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XDoWhileExpression" eSuperTypes="#/3/XAbstractWhileExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="XWhileExpression" eSuperTypes="#/3/XAbstractWhileExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="XTypeLiteral" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#/4/JvmType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrayDimensions" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XInstanceOfExpression" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#/4/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#/3/XExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XThrowExpression" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/3/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XTryCatchFinallyExpression" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="finallyExpression" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="catchClauses" upperBound="-1"
          eType="#/3/XCatchClause" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XCatchClause">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaredParam" eType="#/4/JvmFormalParameter"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XAssignment" eSuperTypes="#/3/XAbstractFeatureCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="assignable" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="staticWithDeclaringType"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XReturnExpression" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/3/XExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="XSynchronizedExpression" eSuperTypes="#/3/XExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="#/3/XExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#/3/XExpression"
          containment="true"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="types" nsURI="http://www.eclipse.org/xtext/common/JavaVMTypes"
      nsPrefix="types">
    <eClassifiers xsi:type="ecore:EClass" name="JvmIdentifiableElement" abstract="true">
      <eOperations name="getIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getSimpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="innerClassDelimiter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmType" abstract="true" eSuperTypes="#/4/JvmIdentifiableElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmVoid" eSuperTypes="#/4/JvmType"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmComponentType" abstract="true"
        eSuperTypes="#/4/JvmType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arrayType" eType="#/4/JvmArrayType"
          containment="true" eOpposite="#/4/JvmArrayType/componentType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmPrimitiveType" eSuperTypes="#/4/JvmComponentType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="simpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmArrayType" eSuperTypes="#/4/JvmComponentType">
      <eOperations name="getDimensions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentType" eType="#/4/JvmComponentType"
          eOpposite="#/4/JvmComponentType/arrayType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmDeclaredType" abstract="true" eSuperTypes="#/4/JvmMember #/4/JvmComponentType">
      <eOperations name="getDeclaredOperations" lowerBound="1">
        <eGenericType eClassifier="#/4/Iterable">
          <eTypeArguments eClassifier="#/4/JvmOperation"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getDeclaredFields" lowerBound="1">
        <eGenericType eClassifier="#/4/Iterable">
          <eTypeArguments eClassifier="#/4/JvmField"/>
        </eGenericType>
      </eOperations>
      <eOperations name="findAllFeaturesByName" lowerBound="1">
        <eGenericType eClassifier="#/4/Iterable">
          <eTypeArguments eClassifier="#/4/JvmFeature"/>
        </eGenericType>
        <eParameters name="simpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getAllFeatures" lowerBound="1">
        <eGenericType eClassifier="#/4/Iterable">
          <eTypeArguments eClassifier="#/4/JvmFeature"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getExtendedInterfaces">
        <eGenericType eClassifier="#/4/Iterable">
          <eTypeArguments eClassifier="#/4/JvmTypeReference"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getExtendedClass" eType="#/4/JvmTypeReference"/>
      <eOperations name="isInstantiateable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="findAllNestedTypesByName">
        <eGenericType eClassifier="#/4/Iterable">
          <eTypeArguments eClassifier="#/4/JvmDeclaredType"/>
        </eGenericType>
        <eParameters name="simpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="isLocal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getDeclaredConstructors" lowerBound="1">
        <eGenericType eClassifier="#/4/Iterable">
          <eTypeArguments eClassifier="#/4/JvmConstructor"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getAllNestedTypes" lowerBound="1">
        <eGenericType eClassifier="#/4/Iterable">
          <eTypeArguments eClassifier="#/4/JvmDeclaredType"/>
        </eGenericType>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="superTypes" upperBound="-1"
          eType="#/4/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
          eType="#/4/JvmMember" containment="true" eOpposite="#/4/JvmMember/declaringType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmTypeParameter" eSuperTypes="#/4/JvmComponentType #/4/JvmConstraintOwner">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declarator" eType="#/4/JvmTypeParameterDeclarator"
          eOpposite="#/4/JvmTypeParameterDeclarator/typeParameters"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmTypeParameterDeclarator" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1"
          eType="#/4/JvmTypeParameter" containment="true" eOpposite="#/4/JvmTypeParameter/declarator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmConstraintOwner" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#/4/JvmTypeConstraint" containment="true" eOpposite="#/4/JvmTypeConstraint/owner"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmTypeConstraint" abstract="true">
      <eOperations name="getIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getSimpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="innerClassDelimiter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeReference" eType="#/4/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#/4/JvmConstraintOwner"
          eOpposite="#/4/JvmConstraintOwner/constraints"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmUpperBound" eSuperTypes="#/4/JvmTypeConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmLowerBound" eSuperTypes="#/4/JvmTypeConstraint"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmAnnotationType" eSuperTypes="#/4/JvmDeclaredType"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmEnumerationType" eSuperTypes="#/4/JvmDeclaredType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
          eType="#/4/JvmEnumerationLiteral" changeable="false" volatile="true" transient="true"
          derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmEnumerationLiteral" eSuperTypes="#/4/JvmField">
      <eOperations name="getEnumType" eType="#/4/JvmEnumerationType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmGenericType" eSuperTypes="#/4/JvmDeclaredType #/4/JvmTypeParameterDeclarator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interface" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strictFloatingPoint"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="anonymous" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmTypeReference" abstract="true">
      <eOperations name="getType" eType="#/4/JvmType"/>
      <eOperations name="getIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getSimpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="innerClassDelimiter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
      </eOperations>
      <eOperations name="accept">
        <eGenericType eTypeParameter="#/4/JvmTypeReference/accept/Result"/>
        <eTypeParameters name="Result"/>
        <eParameters name="visitor">
          <eGenericType eClassifier="#/4/ITypeReferenceVisitor">
            <eTypeArguments eTypeParameter="#/4/JvmTypeReference/accept/Result"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eOperations name="accept">
        <eGenericType eTypeParameter="#/4/JvmTypeReference/accept.1/Result"/>
        <eTypeParameters name="Parameter"/>
        <eTypeParameters name="Result"/>
        <eParameters name="visitor">
          <eGenericType eClassifier="#/4/ITypeReferenceVisitorWithParameter">
            <eTypeArguments eTypeParameter="#/4/JvmTypeReference/accept.1/Parameter"/>
            <eTypeArguments eTypeParameter="#/4/JvmTypeReference/accept.1/Result"/>
          </eGenericType>
        </eParameters>
        <eParameters name="parameter">
          <eGenericType eTypeParameter="#/4/JvmTypeReference/accept.1/Parameter"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmParameterizedTypeReference" eSuperTypes="#/4/JvmTypeReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#/4/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/4/JvmType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmGenericArrayTypeReference" eSuperTypes="#/4/JvmTypeReference">
      <eOperations name="getDimensions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getType" eType="#/4/JvmArrayType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentType" eType="#/4/JvmTypeReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmWildcardTypeReference" eSuperTypes="#/4/JvmTypeReference #/4/JvmConstraintOwner"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmAnyTypeReference" eSuperTypes="#/4/JvmTypeReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/4/JvmType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmMultiTypeReference" eSuperTypes="#/4/JvmCompoundTypeReference"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmMember" abstract="true" eSuperTypes="#/4/JvmAnnotationTarget">
      <eOperations name="internalSetIdentifier" ordered="false" lowerBound="1">
        <eParameters name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="declaringType" eType="#/4/JvmDeclaredType"
          eOpposite="#/4/JvmDeclaredType/members"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#/4/JvmVisibility"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="simpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="deprecated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmFeature" abstract="true" eSuperTypes="#/4/JvmMember">
      <eOperations name="isStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="localClasses" upperBound="-1"
          eType="#/4/JvmGenericType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmField" eSuperTypes="#/4/JvmFeature">
      <eOperations name="getConstantValueAsLong" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eOperations name="getConstantValueAsInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="getConstantValueAsShort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
      <eOperations name="getConstantValueAsByte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
      <eOperations name="getConstantValueAsDouble" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eOperations name="getConstantValueAsFloat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eOperations name="getConstantValueAsChar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
      <eOperations name="getConstantValueAsBoolean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getConstantValueAsString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/4/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="volatile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constantValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmExecutable" abstract="true" eSuperTypes="#/4/JvmFeature #/4/JvmTypeParameterDeclarator">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#/4/JvmFormalParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exceptions" upperBound="-1"
          eType="#/4/JvmTypeReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="varArgs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmConstructor" eSuperTypes="#/4/JvmExecutable"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmOperation" eSuperTypes="#/4/JvmExecutable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#/4/JvmTypeReference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#/4/JvmAnnotationValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="synchronized" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="native" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strictFloatingPoint"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmFormalParameter" eSuperTypes="#/4/JvmAnnotationTarget">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterType" eType="#/4/JvmTypeReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmAnnotationTarget" abstract="true"
        eSuperTypes="#/4/JvmIdentifiableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
          eType="#/4/JvmAnnotationReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmAnnotationReference">
      <eOperations name="getValues" upperBound="-1" eType="#/4/JvmAnnotationValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" eType="#/4/JvmAnnotationType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="explicitValues" upperBound="-1"
          eType="#/4/JvmAnnotationValue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmAnnotationValue" abstract="true">
      <eOperations name="getValueName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#/4/JvmOperation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmIntAnnotationValue" eSuperTypes="#/4/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmBooleanAnnotationValue" eSuperTypes="#/4/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmByteAnnotationValue" eSuperTypes="#/4/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmShortAnnotationValue" eSuperTypes="#/4/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmLongAnnotationValue" eSuperTypes="#/4/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmDoubleAnnotationValue" eSuperTypes="#/4/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmFloatAnnotationValue" eSuperTypes="#/4/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmCharAnnotationValue" eSuperTypes="#/4/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmStringAnnotationValue" eSuperTypes="#/4/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmTypeAnnotationValue" eSuperTypes="#/4/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
          eType="#/4/JvmTypeReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmAnnotationAnnotationValue" eSuperTypes="#/4/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
          eType="#/4/JvmAnnotationReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmEnumAnnotationValue" eSuperTypes="#/4/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" unique="false"
          upperBound="-1" eType="#/4/JvmEnumerationLiteral"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmDelegateTypeReference" eSuperTypes="#/4/JvmTypeReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" eType="#/4/JvmTypeReference"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmSpecializedTypeReference" abstract="true"
        eSuperTypes="#/4/JvmTypeReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="equivalent" eType="#/4/JvmTypeReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmSynonymTypeReference" eSuperTypes="#/4/JvmCompoundTypeReference"/>
    <eClassifiers xsi:type="ecore:EClass" name="JvmUnknownTypeReference" eSuperTypes="#/4/JvmTypeReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmCompoundTypeReference" abstract="true"
        eSuperTypes="#/4/JvmTypeReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#/4/JvmType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
          eType="#/4/JvmTypeReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmCustomAnnotationValue" eSuperTypes="#/4/JvmAnnotationValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JvmInnerTypeReference" eSuperTypes="#/4/JvmParameterizedTypeReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="outer" eType="#/4/JvmParameterizedTypeReference"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="JvmVisibility">
      <eLiterals name="DEFAULT"/>
      <eLiterals name="PRIVATE" value="1"/>
      <eLiterals name="PROTECTED" value="2"/>
      <eLiterals name="PUBLIC" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Iterable">
      <eTypeParameters name="E"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ITypeReferenceVisitor">
      <eTypeParameters name="Result"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ITypeReferenceVisitorWithParameter">
      <eTypeParameters name="Parameter"/>
      <eTypeParameters name="Result"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
